name: Conditions

on: [push]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: npm install, build, and test
        id: run-tests     # we create id for ref for nxt step in IF condition
        run: |
          npm install
          npm run build --if-present
          npm test
      - name: Upload test report
        if: failure() && steps.run-tests.outcome == 'failure'  # if previous step fail then only it will run
        uses: actions/upload-artifact@v3
        with:
          name: dist-without-markdown
          path: |
            dist
            !dist/**/*.md
      - name: Archive code coverage results
        uses: actions/upload-artifact@v3
        with:
          name: code-coverage-report
          path: output/test/code-coverage.html
